version: '3'

services: 
  trojan:
    image: fregie/trojan-go:latest
    ports: 
      - 2443:2443
      - 2522:2522
    volumes:
      - ./trojan-go/server.json:/etc/trojan-go/config.json
      - ./trojan-go/simple.fregie.cn.crt:/etc/ssl/certs/simple.fregie.cn.crt
      - ./trojan-go/simple.fregie.cn.key:/etc/ssl/certs/simple.fregie.cn.key
      - ./trojan-go/data:/opt/trojan

    networks:
      - simple

  adapter-trojan:
    image: fregie/adapter-trojan:latest
    ports:
      - 10001:10001
    environment:
      ADDR: 0.0.0.0:10001
      TROJAN_ADDR: trojan:2552
    volumes: 
      - ./trojan-go/server.json:/server.json

    networks:
      - simple

  simple:
    image: fregie/simple:latest
    ports: 
      - 4433:4433
    volumes:
      - ./config.yaml:/config.yaml

    networks:
      - simple

networks:
  simple:
    driver: bridge