version: '3'

services: 
  trojan:
    image: fregie/trojan-go:latest
    ports: 
      - 2443:2443
      - 2552:2552
    volumes:
      - ./trojan-go/server.json:/etc/trojan-go/config.json
      - ./trojan-go/simple.fregie.cn.crt:/etc/ssl/certs/simple.fregie.cn.crt
      - ./trojan-go/simple.fregie.cn.key:/etc/ssl/certs/simple.fregie.cn.key
      - ./trojan-go/data:/opt/trojan

    networks:
      - simple

  adapter-trojan:
    image: fregie/adapter-trojan:latest
    depends_on:
      - trojan
    ports:
      - 10001:10001
    environment:
      ADDR: 0.0.0.0:10001
      TROJAN_ADDR: trojan:2552
    volumes: 
      - ./trojan-go/server.json:/server.json

    networks:
      - simple

  adapter-shadowsocks:
    image: fregie/adapter-shadowsocks:latest
    ports:
      - 10003:10003
      - 50000-50100:50000-50100
    environment:
      ADDR: 0.0.0.0:10003
      PORT_RANGE: 50000-50100

    networks:
      - simple

  simple:
    image: fregie/simple:latest
    depends_on:
      - adapter-shadowsocks
      - adapter-trojan
      - trojan
    ports: 
      - 4433:4433
      - 4444:4444
      - 4442:4442
    volumes:
      - ./config.yaml:/config.yaml
      - ./simple:/opt/simple

    networks:
      - simple

networks:
  simple:
    driver: bridge