name: Release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

    - name: docker build
      run: docker build -t fregie/simple:$RELEASE_VERSION .

    - name: Push to docker hub :latest
      uses: actions-hub/docker@master
      with:
        args: push fregie/simple:$RELEASE_VERSION



